---
title: "SVM"
author: "YOUR NAME"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
library(tidymodels)


set.seed(1390)
```

## Code from Class:

```{r, echo = FALSE}
# Read data
fed <- read.csv("https://www.dropbox.com/s/9t8sxr1sg0monih/federalist.txt?dl=1")
fed <- fed[,-1]

# Keep numeric section only
fed_all <- as.matrix(fed[,-1])
fed_all <- apply(fed_all, 2, as.numeric)

auths <- fed$Author

# Data from papers with known authors
fed_known <- as.matrix(fed[auths != 'DIS',-1])
fed_known <- apply(fed_known, 2, as.numeric)

auths_known = auths[auths != 'DIS']

# Data from papers with unknown authors
fed_unknown <- as.matrix(fed[auths == 'DIS',-1])
fed_unknown <- apply(fed_unknown, 2, as.numeric)

fed_ex <- as_tibble(fed_known) %>% cbind(auths_known)

fed_matrix <- fed_ex %>% select(-auths_known) %>% as.matrix()
pc <- prcomp(fed_matrix, center = TRUE, scale = TRUE)

fed_pca_df <- pc$x %>%
  as.data.frame() %>%
  mutate(
    author = auths_known
  )

fed_pca_df_uk <- scale(fed_unknown) %>% 
  replace_na(0) %*% 
  pc$rotation %>%
  as_tibble() %>%
  mutate(
    author = "Unknown"
  )

fed_pca_df %>%
  ggplot(aes(x = PC1, y = PC2, color = auths_known)) +
  geom_point()
```



```{r}
fed_pca_df %>%
  ggplot(aes(x = PC1, y = PC2, color = author)) +
  geom_point() +
  geom_abline(slope = 5, intercept = 25) + 
  geom_abline(slope = 6, intercept = 30) +
  geom_abline(slope = 5, intercept = 22) 
```


```{r}
fed_pca_df %>%
  ggplot(aes(x = PC1, y = PC2, color = author)) +
  geom_point() +
  geom_abline(slope = 5, intercept = 23.25) +
  geom_abline(slope = 5, intercept = 20, lty = 2) +
  geom_abline(slope = 5, intercept = 26.5, lty = 2)
```


```{r}
fed_pca_all  <- bind_rows(fed_pca_df, fed_pca_df_uk)

fed_pca_all %>%
  ggplot(aes(x = PC1, y = PC2, color = author)) +
  geom_point() +
  geom_abline(slope = 5, intercept = 23.25) +
  geom_abline(slope = 5, intercept = 20, lty = 2) +
  geom_abline(slope = 5, intercept = 26.5, lty = 2)
```

```{r}
fed_pca_df %>%
  ggplot(aes(x = PC1, y = PC2, color = author)) +
  geom_point() +
  geom_abline(slope = 2, intercept = 2) 
```

```{r}
fed_pca_df %>%
  ggplot(aes(x = PC1, y = PC2, color = author)) +
  geom_point() +
  geom_abline(slope = 2, intercept = 2) +
  geom_abline(slope = 2, intercept = 0, lty = 2) +
  geom_abline(slope = 2, intercept = 4, lty = 2)
```

```{r, echo = TRUE}
svm_spec <- svm_poly(cost = 2, degree = 1) %>%
  set_mode("classification") %>%
  set_engine("kernlab")

fed_recipe <- recipe(author ~ PC1 + PC2, data = fed_pca_df)

fed_wflow <- workflow() %>%
  add_model(svm_spec) %>%
  add_recipe(fed_recipe)

my_svm <- fed_wflow %>%
  fit(fed_pca_df)
```


```{r, echo = TRUE}
fit <- my_svm %>% pull_workflow_fit()
fit
```

```{r, echo = TRUE}
predict(my_svm, fed_pca_df_uk)
```

## Try it!

#### Fit a support vector classifier, tuning the **cost** parameter

#### Fit a support vector **machine**, tuning the **cost** parameter AND the **degree** parameter.

